name: Employee Management CI

on:
  push:
    branches:
      - integrate
      - master

jobs:

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: employee-management-frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - run: npm run build

  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: EmployeeManagement

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - run: mvn clean package